### ISSUE TITLE
parmed.py import clapp broken under anaconda in OS X?

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#181]
It looks like somehow parmed just became incompatible with ipython on anaconda Python on OS X (OR I somehow have something bad in my environment). Here's what I now get if I try to `import parmed`, on a clean install of the latest github (via setup.py):

```
In [1]: import parmed
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-de61dfce161f> in <module>()
----> 1 import parmed

/Users/dmobley/anaconda/bin/parmed.py in <module>()
     20     sys.path.pop(i)
     21
---> 22 from parmed.scripts import clapp
     23 clapp()

ImportError: No module named scripts
```

Oddly, this seems to work fine with normal python but not with ipython. It's not obvious to me why, though I'll try and think about it.

**Comment by swails** [comment]
I saw this with `nose` before, but not with IPython.  What is your `sys.path` variable set to (what is the output of this):

```Python
import sys
print('\n'.join(sys.path))
```
?

I suspect it contains the conda bin directory, in which case `import parmed` is trying to import the `parmed.py` script instead of the `parmed` package.

I'm thinking more and more that I should change the name of `parmed.py` to just `parmed` to avoid this kind of behavior.

**Comment by hainm** [comment]
`cython` and `cython`, not `cython.py`. +1 for `parmed` only script.

**Comment by swails** [comment]
Yea, you brought that up before, too.  I definitely would have preferred that I did that in the first place, I just didn't want to break backwards compatibility (since people actually *are* using `parmed.py`, and this will break scripts).  Technically, @rmcgibbo's fix in #173 should be all that's needed.  But some tools try to be too magical (ipython, nose, ...) and I'm not equipped to combat everyone's magic (<insert some reference to WoW or D&D>).

I think it's best to just make the change now for ParmEd 2.0.

**Comment by davidlmobley** [comment]
@swails - the ouptut you wanted is below and it does NOT contain the conda `bin` directory:

```
/Users/dmobley/anaconda/lib/python2.7/site-packages/mdtraj-1.4.0.dev0-py2.7-macosx-10.5-x86_64.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/openmoltools-0.6.8.dev0-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/alchemical_analysis-0.1.0-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/pymbar-3.0.0.dev0-py2.7-macosx-10.5-x86_64.egg
/Users/dmobley/GoogleDrive/research/github/alchemical-analysis
//Users/dmobley/GoogleDrive/research/github/SolvationToolkit
/Users/dmobley/local/lib/python2.7/site-packages
/Users/dmobley/anaconda/lib/python27.zip
/Users/dmobley/anaconda/lib/python2.7
/Users/dmobley/anaconda/lib/python2.7/plat-darwin
/Users/dmobley/anaconda/lib/python2.7/plat-mac
/Users/dmobley/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/Users/dmobley/anaconda/lib/python2.7/lib-tk
/Users/dmobley/anaconda/lib/python2.7/lib-old
/Users/dmobley/anaconda/lib/python2.7/lib-dynload
/Users/dmobley/anaconda/lib/python2.7/site-packages
/Users/dmobley/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/aeosa
/Users/dmobley/anaconda/lib/python2.7/site-packages/cryptography-0.8-py2.7-macosx-10.5-x86_64.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-macosx-10.5-x86_64.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/openmoltools-0.6.7-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/pymbar-2.1.0b0-py2.7-macosx-10.5-x86_64.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/scripttest-1.3-py2.7.egg
/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg
```

FWIW, there's nothing relevant in local/site-packages.

**Comment by swails** [comment]
Well it's definitely trying to import `parmed.py` as `parmed` (instead of the package).  The traceback shows the parmed.py source.

I think this is just cementing the fact that I have to rename the scripts and drop the .py ending. #182 should fix this once I merge it (although you may have to look for renegade `parmed.py` scripts lying around and nuke them).

Sorry for this confusion.  Growing pains, I suppose.  Things should be much cleaner once this naming change is finished.

**Comment by davidlmobley** [comment]
NP. Once I figured out I could avoid the issue by not using ipython I was OK.

**Comment by swails** [comment]
Yea, except IPython is incredibly convenient, and I don't want parmed to be incompatible with it.  I'll create a new beta release (2.0beta2) after this latest change.

**Comment by swails** [comment]
Should be fixed by #182.

**Comment by hainm** [comment]
@swails 
I created and installed the most updated version. Still get this error.

```
In [1]: import parmed as pmd
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/haichit/anaconda3/envs/dataset_trj/lib/python3.4/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-f3fd6b811cee> in <module>()
----> 1 import parmed as pmd

/u1/haichit/anaconda3/envs/dataset_trj/bin/parmed.py in <module>()
     20     sys.path.pop(i)
     21
---> 22 from parmed.scripts import clapp
     23 clapp()

ImportError: No module named 'parmed.scripts'; 'parmed' is not a package
```

This error does not appear if I am in my home directory. Only happen if I went to some others'. 

Hai

**Comment by hainm** [comment]
oops, I was wrong. The error always appears if I `import parmed as pmd` in the 1st time. if I do that again, it's fine.

**Comment by swails** [comment]
This is the same issue.  Somewhere there is a `parmed.py` script that was installed to a bin directory that IPython (or one of the tools used by IPython) insisted just *had* to be in `sys.path`, and it appears in `sys.path` before `site-packages`.  Which means that `import parmed` tries to import that script instead of the package.

It works the second time because the top of `parmed.py` looks through `sys.path` and deletes all directories containing a `parmed.py` file.  Then it tries to import `parmed`.  But if `parmed.py` itself is imported, the module name is cached and it simply imports itself again.  And fails with this error.

But once it fails, Python is smart enough to know that `parmed` should not be cached and removes it from the module cache.  So when you try to import it again, it skips the directory containing `parmed.py` (since the first time it tried importing `parmed`, the script deleted that folder from `sys.path`), and properly resolves to the package.

What I just found out, though, is that once this happens for the first time, Python generates a compiled `parmed.pyc` file.  Once this happens, deleting `parmed.py` is no longer sufficient, you also have to delete `parmed.pyc`.

In #185, I modified `setup.py` to look through `sys.path` and `os.getenv('PATH')` and deleted any `parmed.py`, `xparmed.py`, `parmed.pyc`, and `xparmed.pyc` files that may be present in any of those directories.  Which *should* avoid this problem from happening again (barring permission errors when trying to delete the pre-existing files, of course).

**Comment by jchodera** [comment]
I think I ran into a similar problem before trying to get the `yank` command-line script installed.

The problem was simple to solve by using the built-in `entry_points` capabilities of `setup.py`.  Not sure if you considered this already:
https://github.com/choderalab/yank/blob/master/setup.py#L145

**Comment by swails** [comment]
That's part of setuptools, not distutils.  The latter is in the stdlib (former is not).  I actually *did* make that change, but then reversed it when I realized that.

**Comment by rmcgibbo** [comment]
It's always an option conditionally import setuptools and use `entry_points`, and fall back to distutils / `scripts` if it's not available. FWIW distutils `scripts` will not work on windows without a `.py` file extension, but setuptools `entry_point` will install the appropriate `.bat` wrapper.

Also, I think `setuptools` _will_ be installed on all PEP453-complaint (the `pip` PEP) pythons, i.e. 2.7.9+ and 3.4+

**Comment by swails** [comment]
Good to know.  I may revisit this, then (after cutting the pre-release).

Thanks!
