### ISSUE TITLE
default behavior of rigid waters is different than in OpenMM

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#624]
In OpenMM, ```createSystem``` has rigid water set to ```True``` by default. While Parmed also has this set to ```True```, there is another option ``` flexibleConstraints=True``` which  adds the bonds and angles regardless of ```constraints``` and calculates those forces and energies while keeping the degrees of freedoms constraint. OpenMM doesn't do this by default. This creates discrepancies in the energies when comparing systems created in OpenMM vs ParmEd.
The output of this script
https://github.com/ChayaSt/openmm/blob/charmm36/devtools/forcefields/charmm/tests/test_ffconversion.py is:
```
pamed energies: [('HarmonicBondForce', 2.238239263973854), ('HarmonicAngleForce', 1.2560985770962343), ('NonbondedForce', -0.17723389838895195), ('CMMotionRemover', 0.0)]
omm eneriges [('HarmonicBondForce', 0.0), ('HarmonicAngleForce', 0.0), ('NonbondedForce', -0.17723389838895195), ('CMMotionRemover', 0.0)]
```
I tried setting ```flexibleConstraints=False```, but I still get the same output.

**Comment by swails** [comment]
I'll look into it.

**Comment by rafwiewiora** [comment]
It's not `flexibleConstraints` that does this - this only applies if you're setting constraints, which you're not. 

You have some problems with how the water behavior is hard coded. Here: https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1999 `rigidWater` is an arg to `omm_bond_force`, but the function doesn't actually use it - looks like you had not-adding the bonds on your mind but didn't code it in. Happy to PR this!

**Comment by swails** [comment]
Good catch!  You are working on plenty of other stuff -- I'll take a stab at this.  Thanks!

**Comment by rafwiewiora** [comment]
Alright, no worries and thanks to you too!

**Comment by swails** [comment]
So I addressed at least one outstanding issue in #638.  Can you check that PR and see if it fixes the issues you reported here?

**Comment by swails** [comment]
I'm pretty sure this is fixed -- feel free to reopen if I'm wrong.

**Comment by ChayaSt** [comment]
I'm sorry I didn't check this PR right away, but I am still seeing the same problem. When I try to run the script with the changes in https://github.com/ParmEd/ParmEd/pull/638, the results are identical as before.
